### ISSUE TITLE
Disable signs (highlight lines only)

### ISSUE THREAD

**Issue by shammellee** [MattesGroeger/vim-bookmarks#124] opened 2017-05-08 06:58 UTC
Is there any way to disable signs? I only want to highlight the lines.

```vim
let g:bookmark_sign = ''  " doesn't work
```

Thanks

**Comment by reorx** [comment] 2019-08-31 06:04
I explored the code and figured out how to disable signs (added a new option `bookmark_sign_disabled`), but because the line highlighting feature relies on the sign (which is actually vim's built-in sign feature), it's not possible to keep line highlight while simply disable the sign. According to my very limited vim knowledge, using match group for lines should be able to achieve that (see [this article](https://lardcave.net/text/Highlighting%20arbitrary%20lines%20in%20Vim.html)), but I'm not experienced enough to refactor in that way.

If you are interested in my implementation (can only disable sign and line highlight simultaneously), tell me and I will upload the code to a fork repo.

**Comment by MattesGroeger** [comment] 2021-08-22 19:23
Duplicate of #91 

Let's continue the discussion in #91 🙏

**Closed by MattesGroeger** 2021-08-22 19:23 UTC
